services:
  # Serviço 1: O Frontend e Servidor Principal em Node.js
  - type: web
    name: assistente-dat-frontend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: GEMINI_API_KEY
        fromService:
          type: web
          name: assistente-dat-retriever
          envVarKey: GEMINI_API_KEY
      # CORREÇÃO: Pedindo o HOST em vez da URL completa
      - key: RETRIEVER_HOST
        fromService:
          type: web
          name: assistente-dat-retriever
          property: host
      # CORREÇÃO: Adicionando a PORTA
      - key: RETRIEVER_PORT
        fromService:
          type: web
          name: assistente-dat-retriever
          property: port

  # Serviço 2: O Serviço de Busca em Python
  - type: web
    name: assistente-dat-retriever
    env: python
    plan: free
    rootDir: ./retriever_service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Cole sua chave de API aqui no painel do Render
